### ISSUE TITLE
fejl ved kanalkonfigurering

### ISSUE THREAD

**Issue by gibman** [clhols/drchannels#16]
har installeret denne her på min shield..
https://www.dropbox.com/s/a4oc5xmtl5naea7/drchannels-tv-release.apk?dl=1

men får fejlen "fejl ved kanalkonfigurering" i live tv kanaler, når jeg forsøger at opsætte kanaler.

Jeg har haft det til at virke tidligere, bare på en tidligere version.

Gør jeg noget forkert ? Eller har DR ændret på API'et ?

**Comment by clhols** [comment]
DR har fjernet API'et til at hente programguiden. Og det ser ikke ud til at den kan hente på anden vis.

**Comment by clhols** [comment]
Har lavet en rettelse på kanalerne vises uden programguide.
