### ISSUE TITLE
Release apk

### ISSUE THREAD

**Issue by trmdi** [clhols/drchannels#19]
Hi,

I am looking for a free/open source IPTV player and found your project looks promised. But why don't you release apk file together with the code? Because many people can't build it. This helps people try your product more easily.

Thank you for a good project. :)

**Comment by trmdi** [comment]
Just tried building it.
But I don't know how to add channels using it? It only shows some preinstalled ones.

**Comment by clhols** [comment]
There are APK files under Github Actions artifacts. The project is for playing channels from the Danish broadcasting compay, not for adding various IPTV channels.
